/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ActiveIdRouteImport } from './routes/active/$id'

const ActiveIdRoute = ActiveIdRouteImport.update({
  id: '/active/$id',
  path: '/active/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/active/$id': typeof ActiveIdRoute
}
export interface FileRoutesByTo {
  '/active/$id': typeof ActiveIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/active/$id': typeof ActiveIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/active/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/active/$id'
  id: '__root__' | '/active/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ActiveIdRoute: typeof ActiveIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/active/$id': {
      id: '/active/$id'
      path: '/active/$id'
      fullPath: '/active/$id'
      preLoaderRoute: typeof ActiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ActiveIdRoute: ActiveIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
